#!/bin/bash
weather=$(cat /tmp/dwm/weather/weather-stat)
weather_count=$(cat /tmp/dwm/weather/weather-stat | wc -c)

if [ "$weather_count" -lt 10 ]; then
	echo $weather;
else
	echo $(cat /tmp/dwm/weather/weather-stat | cut -c1-6)...
fi
