/* Generated by wayland-scanner 1.20.0 */

/*
 * Copyright (c) 2013, 2014 Michael Forney
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface swc_panel_interface;
extern const struct wl_interface swc_screen_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *swc_types[] = {
	NULL,
	NULL,
	NULL,
	&swc_panel_interface,
	&wl_surface_interface,
	NULL,
	&swc_screen_interface,
	NULL,
};

WL_EXPORT const struct wl_interface swc_screen_interface = {
	"swc_screen", 1,
	0, NULL,
	0, NULL,
};

static const struct wl_message swc_panel_manager_requests[] = {
	{ "create_panel", "no", swc_types + 3 },
};

WL_EXPORT const struct wl_interface swc_panel_manager_interface = {
	"swc_panel_manager", 1,
	1, swc_panel_manager_requests,
	0, NULL,
};

static const struct wl_message swc_panel_requests[] = {
	{ "dock", "u?ou", swc_types + 5 },
	{ "set_offset", "u", swc_types + 0 },
	{ "set_strut", "uuu", swc_types + 0 },
};

static const struct wl_message swc_panel_events[] = {
	{ "docked", "u", swc_types + 0 },
};

WL_EXPORT const struct wl_interface swc_panel_interface = {
	"swc_panel", 1,
	3, swc_panel_requests,
	1, swc_panel_events,
};

