/* Generated by wayland-scanner 1.20.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface swc_screen_interface;
extern const struct wl_interface velox_screen_interface;
extern const struct wl_interface velox_tag_interface;

static const struct wl_interface *velox_types[] = {
	NULL,
	&swc_screen_interface,
	&velox_screen_interface,
	NULL,
	&velox_tag_interface,
	&velox_screen_interface,
};

static const struct wl_message velox_requests[] = {
	{ "get_screen", "on", velox_types + 1 },
};

WL_EXPORT const struct wl_interface velox_interface = {
	"velox", 1,
	1, velox_requests,
	0, NULL,
};

static const struct wl_message velox_screen_events[] = {
	{ "focus", "?s?o", velox_types + 3 },
};

WL_EXPORT const struct wl_interface velox_screen_interface = {
	"velox_screen", 1,
	0, NULL,
	1, velox_screen_events,
};

static const struct wl_message velox_tag_events[] = {
	{ "name", "s", velox_types + 0 },
	{ "state", "u", velox_types + 0 },
	{ "screen", "?o", velox_types + 5 },
};

WL_EXPORT const struct wl_interface velox_tag_interface = {
	"velox_tag", 1,
	0, NULL,
	3, velox_tag_events,
};

